DROP FUNCTION IF EXISTS FUNC_GET_PAGINATED_COURSES;

CREATE FUNCTION FUNC_GET_PAGINATED_COURSES(@page INT, @size INT)
    RETURNS TABLE
        AS RETURN
        SELECT *
        FROM course
        ORDER BY course_id
        OFFSET (@page - 1) * @size ROWS FETCH NEXT @size ROWS ONLY;

SELECT *
FROM FUNC_GET_PAGINATED_COURSES(2, 1);