services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - ./mssql:/var/opt/mssql
    environment:
      MSSQL_SA_PASSWORD: Sa@12345678
      ACCEPT_EULA: Y
